config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'welcome/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  paginates_per 5
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 50 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 5
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 2, maximum: 25 }

  VALID_EMAIL_REGX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
    
  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]   
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def index
    @articles = Article.order(:title).page(params[:page])
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    # debugger
    #  render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was successfully created'
      redirect_to article_path(@article)

    else
      render 'new'

      end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have succesfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'There was something wrong with your login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out! '
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]
  def index
    @users = User.order(:username).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
   
  end

  def update   
    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = " User and all articles have been deleted"
    redirect_to users_path 
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "you can only edit your own account"
      redirect_to root_path

    end

  end
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "You need to admin to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class = "row">
    <div class = "col-md-8" style="margin-left: 15%;" >

        <%= form_for (@article), :html => {class: "form", role:"form"} do |f| %>
           <div class= "form-group"> 
                <strong>
                    <%= f.label :title%> 
                </strong>
            </div>
                
                <div class ="col-xs-10">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title here!", autofocus: true %>

                </div>
                <br>
             <div class= "form-group">
                <div >   
                <strong><%= f.label :description %> </strong>
                </div>
                <div class ="col-xs-10">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description here!", autofocus: true %>

                </div>    
            <br>
                <div class= "form-group">           
                    <%= f.submit class: 'col-sm-5 btn btn-primary btn-lg' %> 
                </div>
            
            </div>
        <% end %>

        <div class = "col-cs-4">
           [ <%= link_to "Cancel Request and return to article listing", articles_path %> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align = "center"> Edit Page for article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
 <h1 align="center"> Listing all articles </h1>
 <br/>


<% @articles.each do |article| %>
   
    <div class ="row">
        <div class = "col-sm-8"  align ="center">
            <div class = "well well-lg">
                <div class= "article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class= "article-body">
                  <%= truncate(article.description, length: 100) %>
                     <div class = "article-meta-details">
                          
                        <small> Created by: <%= article.user.username if article.user %>,
                                    <%= time_ago_in_words(article.created_at) %> ago,
                                    last updated: <%= time_ago_in_words(article.updated_at) %> 
                        </small>

                    </div>
                    
                </div>
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <div class = "article-actions">
                        <%= link_to "Edit articles", edit_article_path(article), class: "btn btn-xs btn-primary"  %>
                        <%= link_to 'Delete this article', article_path(article), method: :delete, data: {confirm: "Are you sure?"},  class: "btn btn-xs btn-danger" %>
                        
                    </div>
                <% end %>    
            </div>
        </div>
    </div>

<% end %>

<div align = "center">    
    <ul class="pagination">
            <li class="page-item"> <%= paginate @articles %></li>
        </ul>  
</div>

app/views/articles/new.html.erb
<h1 align = "center"> Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align = "center"> <%= @article.title %></h2> <br />

 <div class ="well col-sm-8">
    <% if @article.user %>
        <ul class =" listing ">
            <div class = " row center">
                <div class = "well col-md-4">
                    <li> Created by:</li>
                    
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class = "article-title">
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>

                    <li> <small> <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></li>

                </div>
            </div>
        </ul>   
    <% end %> 

   <h5 align = "center description" > <strong>Description</strong> </h5>
   <hr>
    <%= simple_format(@article.description) %>

    <div class = "article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit articles", edit_article_path(@article), class: "btn btn-xs btn-primary"  %>
        <%= link_to 'Delete this article', article_path(@article), method: :delete, data: {confirm: "Are you sure?"},  class: "btn btn-xs btn-danger" %>
    <% end %>    
        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success"  %>

    </div>

    <div class ="well col-sm-8">

  
   <hr>
    <div class = "article-actions">
    Created At: <%= @article.created_at %> <br>

    Updated At: <%= @article.updated_at %>
    </div>

   
    
</div>

app/views/layouts/_footer.html.erb
<div class = "container">
    <footer class = "footer">
        <small>
        Copyright &copy: <a href="#"> Subash Khatri </a>
        </small>
    <nav>
        <ul>
            <li class="nav-item" >
                <%= link_to "Articles", articles_path, class: "nav-link" %>
            </li>

        </ul>
    </nav>
    </footer>

</div>

app/views/layouts/_messages.html.erb
<div class = "row ">

    <div class=" col-sm-10">
        <% flash.each do |name, msg| %>
            <div class = 'alert alert-<%="#{name}"%> '>
                 <a href = "#" class = "close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
             
        <% end %>
   
</div>



     

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Subash-blog", root_path, class: "navbar-brand", id:"logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item" >
      <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
       <li class="nav-item">        
          <%= link_to 'Users', users_path, class: "nav-link" %>
        </li>
      <% if logged_in? %>
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <%= link_to "New Article", new_article_path, class:"dropdown-item" %>         
            <div class="dropdown-divider"></div>
            
          </div>
        </li>
        <li class="nav-item">        
          <%= link_to 'logout', logout_path, method: :delete, class: "nav-link" %>
        </li>
       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= 'Admin' if current_user.admin? %>
          </a>

          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %>    
            <%= link_to "view your profile", user_path(current_user), class:"dropdown-item" %>         
            <div class="dropdown-divider"></div>
            
          </div>
        </li>
      <% else %>
        <li class="nav-item">        
          <%= link_to 'login', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">        
          <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
        </li>

      <% end%>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubashBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
<%= render "layouts/navigation" %>

<%= render "layouts/messages" %>
  <div class="container">
    <%= yield %>

  </div>  
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class ="row">
        <div class ="col-xs-8" style="margin-left: 15%; ">
            <div class ="card ">
                <div class ="card-body" style="background-color: rgb(152, 190, 250);">
                    <h2 class ="card-title" style="color:red;">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this from being saved:
                        </h2>
                    <div class = "card-body" style="color:red;">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li> <%= msg %></li>
                            <% end %>
                        <ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class = "row">
    <div class = "col-md-8" style="margin-left: 15%;" >

        <%= form_for (@user), :html => {class: "form", role:"form"} do |f| %>
           <div class= "form-group"> 
                <strong>
                    <%= f.label :username %> 
                </strong>
            </div>
                
                <div class ="col-xs-10">
                    <%= f.text_field :username, class: "form-control", placeholder: "Username here!", autofocus: true %>

                </div>
                <br>
             <div class= "form-group">
                <div >   
                <strong><%= f.label :email %> </strong>
                </div>
                <div class ="col-xs-10">
                    <%= f.email_field :email, class: "form-control", placeholder: "email here!", autofocus: true %>

                </div> 
             <div class= "form-group">
                <div >   
                <strong><%= f.label :password %> </strong>
                </div>
                <div class ="col-xs-10">
                    <%= f.password_field :password, class: "form-control", placeholder: "password !", autofocus: true %>

                </div>        
            <br>
                <div class= "form-group">           
                    <%= f.submit(@user.new_record? ? "Sign Up" : "Update your account", class: 'col-sm-5 btn btn-primary btn-lg') %> 
                </div>
            
            </div>
        <% end %>

        <div class = "col-cs-4">
           [ <%= link_to "Cancel Request and return to user listing", users_path %> ]
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align = "center"> Edit your account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
 <h1 align="center"> Listing all Bloggers </h1>
 <br/>
<div align = "center">

    <% @users.each do |user| %>
    <ul class =" listing ">
        <div class = " row ">
            <div class = "well col-md-4">
                <li><%= link_to gravatar_for(user), user_path(user) %></li>
                <li class = "article-title">
                    <%= link_to user.username, user_path(user) %>
                </li>

                <li> <small> <%= pluralize(user.articles.count, "article") if user.articles %></li>
                <% if logged_in? and current_user.admin? %>
                    <li><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want delete the user and all his article?"}, class: "btn btn-lg btn-danger"%> </li>
                <% end %>

            </div>
        </div>
    </ul>    
    
    
    <% end %>

   
    <ul class="pagination">
            <li class="page-item"> <%= paginate @users %></li>
        </ul>  

</div>
 

app/views/users/new.html.erb
<h1 align = "center"> Signup for Subash-Blog </h1>


<%= render 'form' %>

app/views/users/show.html.erb
<h2 align = "center"> Welcome to <%= @user.username %></h2> <br />

<div class = "row">
    <div class ="well col-sm-8">
        <div class = "col-md-4 center">
            <%= gravatar_for(@user) %>
            <h4 align="center"><%= @user.username %> </h4>
        </div>       
        <hr>
            <div class = "article-actions">
            Created At: <%= @user.created_at %> <br>

            Updated At: <%= @user.updated_at %>
            </div> 

        
        <div class = "article-actions">
        <% if logged_in? && current_user == @user.articles %>
            <%= link_to "Edit User", edit_user_path(@user), class: "btn btn-xs btn-primary"  %>

            <%= link_to 'Delete this user', user_path(@user), method: :delete, data: {confirm: "Are you sure?"},  class: "btn btn-xs btn-danger" %>
        <% end %>    
            <%= link_to "View all users", users_path, class: "btn btn-xs btn-success"  %>

        </div>    
        
    </div>
</div>

app/views/welcome/home.html.erb
<div class=" center jumbotron">
  <h1 class="display-4"> Welcome to Subash Blog! </h1>
  
  <hr class="my-4">


<h1> <%= link_to "Signup", signup_path, class: "btn btn-success btn-lg btn-xlarge" %> !</h1>

</div>